// <auto-generated />
namespace pweb_eCarSharing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class dbStart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbStart));
        
        string IMigrationMetadata.Id
        {
            get { return "201912291654021_dbStart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
